version: "3.8"
services:
  app:
    container_name: geo-math-py
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
    env_file:
      - .env
